"""Nội dung biên soạn cho bản mẫu KHKT; không phải bảng xếp hạng thị trường."""

CAREERS = [
    {"id": "lap-trinh", "name": "Lập trình viên", "category": "Công nghệ", "icon": "code", "color": "mint", "tag": "Xây điều bạn tưởng tượng", "description": "Biến ý tưởng thành website, ứng dụng và những công cụ giúp cuộc sống dễ dàng hơn.", "skills": ["Tư duy logic", "Giải quyết vấn đề", "Làm việc nhóm"], "day": ["Trao đổi với nhóm về tính năng mới", "Viết mã và kiểm tra lỗi", "Thử sản phẩm và nhận phản hồi"], "first_step": "Thử tạo một trang HTML giới thiệu bản thân. Bạn sẽ học được nhiều từ một sản phẩm nhỏ."},
    {"id": "thiet-ke", "name": "Nhà thiết kế đồ họa", "category": "Sáng tạo", "icon": "design", "color": "peach", "tag": "Kể chuyện bằng hình ảnh", "description": "Kết hợp hình ảnh, màu sắc và chữ để truyền tải một thông điệp thật rõ ràng.", "skills": ["Quan sát", "Tư duy hình ảnh", "Lắng nghe"], "day": ["Tìm hiểu thông điệp cần truyền tải", "Phác thảo và thử nhiều cách thể hiện", "Chỉnh sửa thiết kế theo phản hồi"], "first_step": "Thiết kế một poster cho sự kiện ở lớp; thử hai cách bố trí và hỏi bạn bè cách nào dễ đọc hơn."},
    {"id": "bac-si", "name": "Bác sĩ", "category": "Y tế", "icon": "health", "color": "blue", "tag": "Hiểu để chăm sóc", "description": "Lắng nghe, thăm khám và phối hợp cùng đồng nghiệp để chăm sóc sức khỏe người bệnh.", "skills": ["Kiến thức khoa học", "Đồng cảm", "Cẩn thận"], "day": ["Thăm khám và trao đổi với người bệnh", "Hội chẩn, ghi chép hồ sơ", "Theo dõi điều trị; một số vị trí có ca trực"], "first_step": "Tìm hiểu môn Sinh học và tham gia một buổi hướng nghiệp cùng nhân viên y tế."},
    {"id": "giao-vien", "name": "Giáo viên", "category": "Giáo dục", "icon": "book", "color": "yellow", "tag": "Thắp lên sự tò mò", "description": "Thiết kế trải nghiệm học tập và giúp mỗi học sinh tìm ra cách học phù hợp với mình.", "skills": ["Giao tiếp", "Kiên nhẫn", "Tổ chức"], "day": ["Chuẩn bị hoạt động và bài giảng", "Hướng dẫn học sinh trong lớp", "Nhận xét bài làm và hỗ trợ học sinh"], "first_step": "Thử giải thích một kiến thức bạn thích cho bạn cùng lớp bằng ví dụ dễ hiểu."},
    {"id": "ky-su-moi-truong", "name": "Kỹ sư môi trường", "category": "Kỹ thuật", "icon": "leaf", "color": "mint", "tag": "Ý tưởng cho hành tinh xanh", "description": "Tìm giải pháp xử lý nước, chất thải và sử dụng tài nguyên có trách nhiệm hơn.", "skills": ["Phân tích", "Khoa học tự nhiên", "Tư duy hệ thống"], "day": ["Lấy mẫu hoặc xem dữ liệu môi trường", "Phân tích và đề xuất giải pháp", "Theo dõi hiệu quả hệ thống xử lý"], "first_step": "Quan sát cách phân loại rác tại trường và đề xuất một thay đổi nhỏ có thể đo lường."},
    {"id": "truyen-thong", "name": "Người làm truyền thông", "category": "Sáng tạo", "icon": "chat", "color": "peach", "tag": "Kết nối bằng câu chuyện", "description": "Hiểu người đọc và tạo nội dung để đưa câu chuyện của một tổ chức đến đúng người.", "skills": ["Viết", "Lắng nghe", "Lập kế hoạch"], "day": ["Tìm hiểu người đọc và chủ đề", "Viết, biên tập hoặc sản xuất nội dung", "Theo dõi phản hồi và điều chỉnh"], "first_step": "Viết một bài ngắn về hoạt động của lớp, kiểm tra thông tin trước khi chia sẻ."},
]

ARTICLES = [
    {"id": "chua-biet-thich-gi", "title": "Chưa biết mình thích gì? Bắt đầu từ những điều nhỏ.", "category": "Hiểu bản thân", "minutes": 4, "color": "peach", "number": "01", "summary": "Bạn không cần có ngay một câu trả lời lớn cho tương lai.", "body": ["Chưa biết mình muốn làm nghề gì là một điểm bắt đầu bình thường. Thay vì tìm ngay một nghề duy nhất, hãy quan sát những hoạt động khiến bạn tò mò.", "Trong một tuần, ghi lại ba điều: việc bạn thích làm, việc bạn thấy mình tiến bộ và điều bạn muốn tìm hiểu thêm. Không cần chấm điểm hay so sánh với bạn bè.", "Chọn một hoạt động nhỏ để thử: làm poster, viết một trang web, giải thích một bài học hoặc chăm sóc một góc cây. Sau đó tự hỏi: mình thích phần nào và muốn thử tiếp điều gì?", "Trao đổi với thầy cô hoặc người thân về điều bạn quan sát được. Sở thích có thể thay đổi khi bạn có thêm trải nghiệm."]},
    {"id": "nghe-hot", "title": "Nghề “hot” có phải là nghề phù hợp với bạn?", "category": "Khám phá nghề", "minutes": 3, "color": "mint", "number": "02", "summary": "Đừng chỉ nhìn tên nghề. Hãy tìm hiểu một ngày làm việc.", "body": ["Một nghề được nhắc đến nhiều chưa chắc phù hợp với mọi người. Điều quan trọng là bạn hiểu công việc thường ngày, môi trường và những kỹ năng cần rèn luyện.", "Hãy đặt ba câu hỏi: người làm nghề này thực sự làm gì, họ gặp khó khăn nào và mình có muốn học những kỹ năng đó không?", "Tìm hiểu từ nhiều nguồn và trò chuyện với người đang làm nghề. Các thông tin về nhu cầu tuyển dụng và thu nhập cần có nguồn, thời điểm và địa điểm cụ thể.", "Các nghề nổi bật trên website này là nội dung khám phá của bản mẫu, không phải bảng xếp hạng tuyển dụng. Bạn có thể bắt đầu từ một nghề khiến mình tò mò."]},
    {"id": "hoi-nguoi-lam-nghe", "title": "5 câu hỏi để trò chuyện với người đang làm nghề.", "category": "Kỹ năng tương lai", "minutes": 3, "color": "blue", "number": "03", "summary": "Một cuộc trò chuyện có thể mở ra một góc nhìn mới.", "body": ["1. Một ngày làm việc điển hình của cô/chú/anh/chị diễn ra như thế nào?", "2. Phần việc nào thú vị nhất, và phần nào khó nhất?", "3. Những kỹ năng nào được sử dụng thường xuyên?", "4. Có điều gì về nghề mà học sinh thường hiểu nhầm?", "5. Nếu bắt đầu tìm hiểu từ bây giờ, em nên thử hoạt động nhỏ nào?", "Xin phép trước khi ghi âm hoặc chia sẻ câu chuyện. Sau cuộc trò chuyện, ghi lại điều bất ngờ và điều bạn muốn tìm hiểu thêm."]},
]
